#!/bin/sh
# postinst script for emuccan
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
      curdir=`pwd`
      # this seems like a lot of work; hopefully only one kernel is present
      for i in /lib/modules/* ; do
        cd $i
        depmod -A
      done
      cd $curdir

      modprobe emuc2socketcan

      # reload udev rules, may have to reboot, sadly:
      udevadm control --reload-rules && udevadm trigger

      # enable emuccan.service
      systemctl enable emuccan
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
