#!/bin/bash
# Bash script to remove the old module f18601 and install the new one generated by dkms
# This script is used in the post_install.sh file of the debian package
MODULE_NAME="emuccan"

KVER=`uname -r`
if [ "$(grep -c "^${MODULE_NAME}" /proc/modules)" -ne 0 ]; then
    modprobe -r f81601
fi

rm /etc/depmod.d/${MODULE_NAME}.conf || true
rm /etc/modules-load.d/${MODULE_NAME}.conf || true
